### ISSUE TITLE
No such file or directory,error on raspberry pi  3b

### ISSUE THREAD

**Issue by muazzammullah** [hanckmann/matrixdriver#1]
File "light.py", line 15, in <module>
    md.draw(iterations=3)
  File "/home/pi/.local/lib/python3.5/site-packages/matrixdriver/matrixdriver.py", line 244, in draw
    self.spi.open(self.bus, self.device)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by hanckmann** [comment]
There is not much information to go on, but first check if you performed the following actions:
1) enable SPI (https://www.raspberrypi.org/documentation/hardware/raspberrypi/spi/README.md)
2) install requirements.txt in pythong (pip install -r requirements.txt)
3) make sure you are actually on the RPi (I have tested this on the RPi3, but as far as I know it should also work on the other versions with GPIO ports)
4) make sure you read the README.md and test the actual example application as described there.

If you checked that you followed these steps. If it still does not work afterwards, let me know and I will have another look. If it does work afterwards, please post what the issue was (that might help others in the future as well).

~~~
