### ISSUE TITLE
1 for switch on/off?

### ISSUE THREAD

**Issue by cocoacube** [hanckmann/matrixdriver#3]
Hello Patrick, thanks for this driver. It is cool.

I notice that when I set a frame with 8x8 list with value 1, no led was switched on. Did I miss anything or you might have to update the comments in the code "in which an interger value of 0 represents to *not* switch on the LED."

Are we able to set RGB values of each LED?

**Comment by hanckmann** [comment]
Did you try the send_frame example (https://github.com/hanckmann/matrixdriver#send-frame)?
A 1 implies switching on and a 0 implies switching off a led. Since we are talking about a color led matrix, we need to provide this for each color. Therefore you need to provide three (3) frames:
`frames(red=frame1, green=frame2, blue=frame3)`
I am considering to add a different interface in which you can provide a matrix of RGB values as tuple/list. This might make things easier to understand... let me know what you think (or provide a pull request).

**Comment by isaacmorph** [comment]
Hi, I have the same issue, i.e. value "0" lights the LED. Could it be a different LED matrix hardware?
Also, if I edit your send_frame example, the LEDs are lit in a mirrored fashion. For example, when I send this row for the red frame: [0, 1, 1, 1, 1, 0, 0, 0]  the LEDs will light up like: [0, 0, 0, 1, 1, 1, 1, 0] ("0" means lit and "1" off).
Otherwise, great work! This is exactly what I am looking for to be able to drive my matrix.

**Comment by cocoacube** [comment]
@hanckmann Sorry for the late reply. Got very busy recently.
I used the data as follows:

frame = [[1, 0, 1, 0, 1, 0, 1, 0],
         [0, 1, 0, 1, 0, 1, 0, 1],
         [1, 0, 1, 0, 1, 0, 1, 0],
         [0, 1, 0, 1, 0, 1, 0, 1],
         [1, 0, 1, 0, 1, 0, 1, 0],
         [0, 1, 0, 1, 0, 1, 0, 1],
         [1, 0, 0, 0, 1, 0, 1, 0],
         [0, 1, 0, 0, 0, 1, 0, 1]]

And I used a while loop to make it keep running:

while(True):
    md.frames(red=frame, green=frame, blue=frame) 
    md.draw(iterations=300)

The result is in the picture I attached.
![img_1491](https://user-images.githubusercontent.com/5778478/35616015-de8c204e-06ae-11e8-9ecb-edd95c9a4f76.JPG)

I expected to get a result of LEDs on and off one after another. The color should be white. But it is not (all RED color). Also something is very strange. If you look at the column at left side, you will see 
the first column is alternatively on and off.

Get any clue which part I did wrong and have a solution for that?
